### ISSUE TITLE
Endless Canyon elevator sporadically invisible

### ISSUE THREAD

**Issue by Ixrec** [StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider#26]
Some of my Archipelago Randomizer players have recently reported this elevator being invisible, similar to https://github.com/TRSasasusu/TranslationForTheOutsider/issues/22 despite that being from 2023 and [allegedly fixed already](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/blob/d712ff05651b87b747d3c31f90c1109583b414a5/TheOutsiderFixes/BugFixPatches.cs#L372).

The Randomizer contains an item called "Raft Docks Patch" which does call `.GoDown()` on this elevator, so I thought this was my bug when the reports first came in. However we've since confirmed that whether the randomizer item matters varies from player to player, and at least one of the affected players observed it without the randomizer mod, and nobody reported this until June 9th 2025, so I currently believe it to be an Outsider bug (perhaps introduced by the most recent base game update?) that's merely being noticed more by randomizer players.

![Image](https://github.com/user-attachments/assets/2faf1f6e-2be4-4baf-b85f-54540702a7f9)

![Image](https://github.com/user-attachments/assets/79243ffe-8008-4abd-b448-00c0db850b09)

![Image](https://github.com/user-attachments/assets/5b2cf507-a176-4050-b476-3d138ee5c7eb)

And once we realized it had to do with the Outsider, I was also able to reproduce:

![Image](https://github.com/user-attachments/assets/6f711824-c81e-4d3a-a99e-63ecbea412a3)

(not that I'm expecting a fix at this point, but I don't want to be one of those users who never reports bugs)

**Comment by TRSasasusu** [comment]
@Ixrec  I tested it:

* Only The Outsider: The elevator exists. There is no problem.
* The Outsider with New Horizons: The elevator is duplicated as Kinrah wrote.

I cannot reproduce the complete disappearance of the elevator. How did you reproduce it?

**Comment by Ixrec** [comment]
I'm not sure if it's deterministic enough that I can answer that question. But what I can tell you is:

my full mod list was:
```json
[
  "Vesper.UnityExplorer",
  "SBtT.TheOutsider",
  "xen.EnableMeditation",
  "Heelio.EotEBrighterDreams",
  "dgarro.CustomShipLogModes",
  "JohnCorby.VanillaFix",
  "Ixrec.ArchipelagoRandomizer",
  "clubby789.OWClock",
  "Glitch.AltDebugMenu",
  "xen.CommonCameraUtility",
  "dgarro.SuitLog"
]
```
so I guess NH isn't strictly required, but maybe NH and the randomizer are both doing something relevant and either one suffices to reproduce???

I used the cheat mod's advanced warps (71 and 74) to get to DW quickly, and F2 to use the spacesuit in DW.

Exact repro steps would be tricky since I had the randomizer mod connected to an Archipelago multiworld, and enabled the randomizer's "Raft Docks Patch" item, and I never personally attempted to reproduce this outside of the randomizer (it was other players who claimed to be able to do that). However, you can probably ignore all that setup and reproduce [the relevant effect of the item](https://github.com/Ixrec/OuterWildsArchipelagoRandomizer/blob/c166770230562a8d7ceadc84c99afe224e394ac7/mod/ItemImpls/DLCProgression/SimulationDocks.cs#L64C9-L65C62) by running 
```cs
var ecDockElevator = GameObject.Find("DreamWorld_Body/Sector_DreamWorld/Sector_DreamZone_3/Interactibles_DreamZone_3/Elevator_Raft/Prefab_IP_DW_CageElevator");
ecDockElevator.GetComponent<CageElevator>().GoDown();
```
in UE's console.

**Comment by TRSasasusu** [comment]
@Ixrec  In

```
[
  "clubby789.OWClock",
  "Glitch.AltDebugMenu",
  "Bwc9876.TimeSaver",
  "Vesper.UnityExplorer",
  "SBtT.TheOutsider"
]
```

I tested

```csharp
var ecDockElevator = GameObject.Find("DreamWorld_Body/Sector_DreamWorld/Sector_DreamZone_3/Interactibles_DreamZone_3/Elevator_Raft/Prefab_IP_DW_CageElevator");
ecDockElevator.GetComponent<CageElevator>().GoDown();
```

when I entered the dream world from the hidden gorge and Friend's structure because it seems be called in that time on your code. However, it had no problem; the elevator correctly went to the bridge.

**Comment by TRSasasusu** [comment]
As I wrote in the discord, I also tested it with

```
[
  "clubby789.OWClock",
  "xen.CommonCameraUtility",
  "Heelio.EotEBrighterDreams",
  "dgarro.CustomShipLogModes",
  "JohnCorby.VanillaFix",
  "Vesper.UnityExplorer",
  "dgarro.SuitLog",
  "SBtT.TheOutsider",
  "Glitch.AltDebugMenu",
  "xen.EnableMeditation"
]
```

but, there was no problem, as in my previous comment.

**Comment by Ixrec** [comment]
Unfortunately Kinrah does not have a github account, so cross-posting from Discord:

> Kinrah — 01:45
> **Confirmed not-AP related.**
> straight in via the breach, top of the lift, and it left a ghost of itself when I sent it down to the docks.
> activated mods are as follows:
> ```
> Cheat and Debug Menu
> Clock
> Common Camera Utility
> Custom Ship Log Modes
> Enable Meditation
> Hearth's Neighbor
> Hearth's Neighbor 2: Magistarium
> Mod Jam 3
> New Horizons
> Peaceful Ghosts
> Power Failure
> Suit Log
> The Outsider
> Vanilla Fix
> ```
> I don't see any errors in the game log that seem relevant.

**Comment by TRSasasusu** [comment]
~~I think Interstellar Mode has not been considered in The Outsider.~~
~~In particular, Mod Jam 3 makes us start on the Mod Jam 3 system, and it would break many things because The Outsider cannot use `newHorizons.GetCurrentStarSystem()`.~~

~~Should this issue be resolved in The Outsider?~~

**Now, The Outsider checks whether the star system is a base game system in NewHorizonsCompat.cs.**

**Comment by TRSasasusu** [comment]
Note: actually, The Outsider can use `newHorizons.GetCurrentStarSystem()` by conditioned `ModHelper.Interaction.ModExists("xen.NewHorizons");`, though.

**Comment by KinrahCOAL** [comment]
Thought I might as well just create an account to stop filling up the AP thread with something that isn't AP related... In response to Interstellar Mode, I tried disabling Mod Jam 3, HN1 and HN2, but the issue remains.

**Comment by KinrahCOAL** [comment]
I did some back and forth testing enabling various mods and I've narrowed it down.

The Outsider by itself - no bug.
New Horizons by itself (with its dependencies) - no bug.
The Outsider AND New Horizons (and its dependencies) - bug.

**Comment by TRSasasusu** [comment]
>The Outsider AND New Horizons (and its dependencies) - bug.

What does a bug occur? I have already tested it in The Outsider AND New Horizons (of course, with its dependencies), and only the duplicated elevator bug occurred.

**Comment by KinrahCOAL** [comment]
> > The Outsider AND New Horizons (and its dependencies) - bug.
> 
> What does a bug occur? I have already tested it in The Outsider AND New Horizons (of course, with its dependencies), and only the duplicated elevator bug occurred.

That was the one I was talking about.

**Comment by TRSasasusu** [comment]
Ok. I think it can be fixed in the next release.
On the other hand, could you reproduce the elevator disappearance bug? (See the 1st comment: https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/issues/26#issue-3166241007 )

**Comment by KinrahCOAL** [comment]
No, I can't. I added Brighter Dreams as in Ixrec's modlist, ran a solo AP game with the docks patch and used the cheat mod's warps, but I still see the duplicated bug behaviour (with the real elevator at the bottom and a fake one with no collision at the top).

**Comment by TRSasasusu** [comment]
@KinrahCOAL Could you test this build: https://github.com/TRSasasusu/Outer-Wilds-The-Outsider/releases/tag/v1.1.9 ?
It fixes the elevator duplication issue.

**Comment by KinrahCOAL** [comment]
I don't have time to test it with AP right now, but a regular game with Outsider and NH enabled now did not result in the bug, so it appears to have worked.

**Comment by TRSasasusu** [comment]
@KinrahCOAL Thank you!! It is released in [v1.1.9](https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/releases/tag/v1.1.9).
